"use client";

import { Button } from "@/components/ui/button";
import { FileText, Loader2 } from "lucide-react";
import { useState } from "react";
import { jsPDF } from "jspdf";
import { domToPng } from "modern-screenshot";

interface PrintButtonProps {
    targetId?: string;
}

export function PrintButton({ targetId = "audit-report" }: PrintButtonProps) {
    const [isGenerating, setIsGenerating] = useState(false);

    const handleDownload = async () => {
        const element = document.getElementById(targetId);
        if (!element) return;

        setIsGenerating(true);

        // 1. Create Overlay Mask
        const mask = document.createElement("div");
        mask.style.position = "fixed";
        mask.style.inset = "0";
        mask.style.backgroundColor = "#ffffff";
        mask.style.zIndex = "9999";
        mask.style.display = "flex";
        mask.style.alignItems = "center";
        mask.style.justifyContent = "center";
        mask.style.fontSize = "1.5rem";
        mask.style.color = "#0f172a";
        mask.innerHTML = `<div class="flex flex-col items-center gap-4"><svg class="animate-spin h-10 w-10 text-blue-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path></svg><span>Preparing Audit Report...</span></div>`;
        document.body.appendChild(mask);

        // 2. Clone and Position Element "On Screen" (behind mask)
        const clone = element.cloneNode(true) as HTMLElement;
        clone.removeAttribute("id"); // Avoid ID conflicts
        clone.classList.add("pdf-mode");

        clone.style.position = "absolute";
        clone.style.top = "0";
        clone.style.left = "0";
        // Force desktop width for consistent layout
        clone.style.width = "1280px";
        clone.style.zIndex = "9998"; // Behind mask
        clone.style.backgroundColor = "#ffffff";

        document.body.appendChild(clone);

        // 3. Wait for layout
        await new Promise(r => setTimeout(r, 800)); // Slightly longer to ensure full render

        // 4. Force Apply Styles (Inline) to ensure they take effect
        // Hide elements
        const hiddenElements = clone.querySelectorAll(".pdf-hide") as NodeListOf<HTMLElement>;
        hiddenElements.forEach(el => el.style.setProperty("display", "none", "important"));

        // Show elements
        const showElements = clone.querySelectorAll(".pdf-show") as NodeListOf<HTMLElement>;
        showElements.forEach(el => el.style.setProperty("display", "block", "important"));

        // Center text
        const centerElements = clone.querySelectorAll(".pdf-text-center") as NodeListOf<HTMLElement>;
        centerElements.forEach(el => {
            el.style.setProperty("text-align", "center", "important");
            el.style.setProperty("width", "100%", "important");
        });

        // Header layout
        const headerLayouts = clone.querySelectorAll(".pdf-header-layout") as NodeListOf<HTMLElement>;
        headerLayouts.forEach(el => {
            el.style.setProperty("flex-direction", "column", "important");
            el.style.setProperty("justify-content", "center", "important");
            el.style.setProperty("align-items", "center", "important");
            el.style.setProperty("gap", "10px", "important");
        });

        try {
            const dataUrl = await domToPng(clone, {
                scale: 2,
                backgroundColor: '#ffffff',
            });

            const img = new Image();
            img.src = dataUrl;
            await new Promise((resolve) => { img.onload = resolve; });

            const pdf = new jsPDF("p", "mm", "a4");
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();

            const margin = 10;
            const contentWidth = pdfWidth - (2 * margin);
            const contentHeight = pdfHeight - (2 * margin);

            const imgWidth = img.width;
            const imgHeight = img.height;

            const ratio = contentWidth / imgWidth;
            const scaledHeight = imgHeight * ratio;

            let heightLeft = scaledHeight;
            let position = margin;
            let page = 0;

            const addFooter = () => {
                pdf.setFontSize(8);
                pdf.setTextColor(100);
                pdf.text("Report generated by flowaudit.com", pdfWidth / 2, pdfHeight - 10, { align: "center" });
            };

            pdf.addImage(dataUrl, "PNG", margin, position, contentWidth, scaledHeight);
            addFooter();

            heightLeft -= contentHeight;

            while (heightLeft > 0) {
                page++;
                position = margin - (page * contentHeight);
                pdf.addPage();
                pdf.addImage(dataUrl, "PNG", margin, position, contentWidth, scaledHeight);
                addFooter();
                heightLeft -= contentHeight;
            }

            pdf.save(`audit-report-${new Date().toISOString().split('T')[0]}.pdf`);
        } catch (error) {
            console.error("PDF Generation failed:", error);
        } finally {
            // 4. Cleanup
            if (document.body.contains(clone)) document.body.removeChild(clone);
            if (document.body.contains(mask)) document.body.removeChild(mask);
            setIsGenerating(false);
        }
    };

    return (
        <Button variant="outline" onClick={handleDownload} disabled={isGenerating}>
            {isGenerating ? (
                <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Generating PDF...
                </>
            ) : (
                <>
                    <FileText className="w-4 h-4 mr-2" />
                    Download Report
                </>
            )}
        </Button>
    );
}
